DROP TABLE PAYMENT CASCADE CONSTRAINTS;
/
DROP TABLE EMP CASCADE CONSTRAINTS;
/

-----------------CREATING TABLES-------------------
CREATE TABLE EMP (
    EMP_ID INTEGER CONSTRAINT PK_EMP_ID PRIMARY KEY,
    EMP_EMAIL VARCHAR(20),
    EMP_USERNAME VARCHAR2(20) UNIQUE NOT NULL,
    EMP_PASSWORD VARCHAR2(20) NOT NULL,
    EMP_MANAGER_ID INTEGER
);
/

CREATE TABLE PAYMENT(
    PAY_ID INTEGER CONSTRAINT PK_PAY_ID PRIMARY KEY,
    PAY_AMOUNT NUMBER(6,2),
    PAY_STATUS VARCHAR2(1) DEFAULT 'P' CHECK(PAY_STATUS IN ('P','A','D')),
    EMP_ID INTEGER REFERENCES EMP(EMP_ID)
);
/

-----------CREATING SEQUENCES AND TRIGGERS---------
CREATE SEQUENCE SQ_EMPS_PK
START WITH 1
INCREMENT BY 1;
/

CREATE OR REPLACE TRIGGER TR_INSERT_EMPS
BEFORE INSERT ON EMP
FOR EACH ROW
BEGIN
    SELECT SQ_EMPS_PK.NEXTVAL INTO :NEW.EMP_ID
    FROM DUAL;
END;
/

CREATE SEQUENCE SQ_PAYMENTS_PK
START WITH 1
INCREMENT BY 1;
/

CREATE OR REPLACE TRIGGER TR_INSERT_PAYMENTS
BEFORE INSERT ON PAYMENT
FOR EACH ROW
BEGIN
    SELECT SQ_PAYMENTS_PK.NEXTVAL INTO :NEW.PAY_ID
    FROM DUAL;
END;
/

---------------MISC--------------------------------
INSERT INTO EMP VALUES (1,'kd123@revature.com' ,'kd123','pw123',1); 
INSERT INTO EMP VALUES (2, 'sherlockH@gmail.com', 'sholmes456', 'watson321', 0);
INSERT INTO EMP VALUES (3, 'tstark3000', 'tonys789', '3000', 0);
INSERT INTO EMP VALUES (4, 'bwayne@gmail.com', 'brucew654', 'batman123', 1);

SELECT * FROM EMP;
SELECT * FROM PAYMENT;

INSERT INTO PAYMENT VALUES (1, 1500.00, 'P', 1);
INSERT INTO PAYMENT VALUES (2,8000.00,'A', 2); 
INSERT INTO PAYMENT VALUES (3, 5000.00, 'P', 3);
INSERT INTO PAYMENT VALUES (4, 3000.00, 'D', 4);

-- LOCATING DUPLICATE OBJS
SELECT *

FROM all_objects

WHERE object_name = ‘EMPLOYEES’;

--ADDING FK CONSTRAINT
ALTER TABLE PAYMENT
ADD CONSTRAINT FK_EMP_ID
FOREIGN KEY (EMP_ID) REFERENCES EMP(EMP_ID);
/
/* creating sequences for primary keys */
DROP SEQUENCE SQ_EMPS_PK;
/

DROP SEQUENCE SQ_PAYMENTS_PK;
/

