-----------------CREATING TABLES-------------------
CREATE TABLE EMPLOYEE(
    EMP_ID NUMBER(6) CONSTRAINT PK_EMP PRIMARY KEY,
    FNAME VARCHAR2(150),
    LNAME VARCHAR(150),
    MAN_ID NUMBER(6),
    PSWRD VARCHAR2(255),
	USERNAME VARCHAR(255)
);

CREATE TABLE MANAGER(
    MAN_ID NUMBER(6) CONSTRAINT PK_MAN_ID PRIMARY KEY,
    NAME VARCHAR2(150),
	PSWRD VARCHAR2(255),
	USERNAME VARCHAR(255)
);

CREATE TABLE REIMBURSMENT(
    REIMB_ID NUMBER(5) CONSTRAINT PK_REIM PRIMARY KEY,
    EMP_ID NUMBER(6),
    STATUS VARCHAR2(25),
    DESCRIPTION VARCHAR2(255),
    RESOLVED_BY NUMBER(6)
);


