-- CREATE TABLES

-- DATA FOR COURSES TABLE
INSERT INTO COURSES VALUES(1, 'Physics');
INSERT INTO COURSES VALUES(2, 'Chemistry');

-- DATA FOR STUDENTS TABLE
INSERT INTO STUDENTS VALUES(1, 'Bonny');
INSERT INTO STUDENTS VALUES(2, 'Clyde');

-- DATA FOR STUDENT AND COURSE TABLE
INSERT INTO STUDENTS_COURSES VALUES(1,1);
INSERT INTO STUDENTS_COURSES VALUES(1,2);
INSERT INTO STUDENTS_COURSES VALUES(2,2);